sudo: required
language: elixir
elixir:
  - 1.10
opt_release:
  - 22.2.6
addons:
  postgres: "9.4"
services:
  - postgres
cache:
  directories:
    - _build
    - deps
script:
  - mix format --check-formatted --dry-run

